# Generated by Django 3.0.6 on 2020-05-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banglorejobs',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
