# Generated by Django 3.0.6 on 2020-05-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200530_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banglorejobs',
            name='phonenumber',
        ),
    ]
